---
title: "Constraints with branching"
author: "CulturalSystems"
date: "2024-02-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages and Functions

```{r}
library(igraph)
library(extraDistr)
library(matrixStats)
library(Rcpp)
library(dplyr)
library(ggplot2)

source("simFunctions.R")
source("loopFunctions.R")
```

## Set Parameters

```{r simulation parameters}
#### simulation parameters
params <- list(
  num_nodes = 16,                 # size of the cultural systems (number of nodes)
  root_node = 1,                  # root node of the tree
  N = 100,                        # population size
  M = 10,                         # number of demonstrators
  timesteps =  2000,              # number of time steps in the simulation
  S = 0.99,                       # reliance on social learning; (1-S) is innovation rate
  reset_rate = 0.05,             # probability that an individual is replaced by a naive individual
  payoff_scaling = 1,             # Constant that is added/subtracted for each step away from the root node
  payoff_weight = 0.5,              # How much payoff depends on randomness vs distance from the root node (0=random, 1=deterministic))
  blockedLayer = 1,               # layer at which tree blockages occur
  numBlocked = 1,                 # number of blocked traits in the model
  propBlocked = 0.0,              # proportion of individuals that have blocked traits
  numSteps = 3,                   # number of auxiliary traits necessary for overcoming a block
  detourType = "parallel",        # type of detour (parallel or serial)
  typical_learning_strategy = 1,  # social learning strategy used by unblocked learners
  get_tr_sums = TRUE,             # save trait distributions (Only do this if when running one simulation at a time)
  data_path = "./data/",
  age_bias = 0.5, 
  tree_func = 1                   # 0 for flat, 1 for constrained
)
``` 

## Run Simulation

```{r}
set.seed(1)
tree <- generate_rooted_tree()
num_cores <- parallel::detectCores()
future::plan(future::multisession, workers = ifelse(num_cores > 1, num_cores - 1, 1))

start_time <- Sys.time()
expand.grid(learningStrategy = c(0:2, 4,5),
            numSteps = c(1, 2, 3),
            blockedLayer = c(1, 2, 3),
            #propBlocked = 0.02,
            propBlocked = round(seq(0.02, 1, length.out = 50),2),
            repl = 1,
            age_bias = round(seq(0, 1, length.out = 25),2),
            tree_func = 0) %>% 
run_all_simulations_parallel(params, tree) %>% 
saveRDS("./data/strategySuccess.rds")
end_time <- Sys.time()
future::plan(future::sequential)

end_time - start_time
beepr::beep(3)
```

## Sequential Execution
For debugging and testing

```{r}
set.seed(1)
tree <- generate_rooted_tree()

res <- expand.grid(learningStrategy = c(0:2, 4,5),
            numSteps = c(1, 2, 3),
            blockedLayer = c(3),
            #propBlocked = 0.1,
            propBlocked = round(seq(0.02, 1, length.out = 50),2),
            repl = 1,
            age_bias = 0,
            #age_bias = round(seq(0, 1, length.out = 25),2),
            tree_func = c(0)) %>%
  run_all_simulations(params, tree) #%>%
  saveRDS("strategySuccess_3.rds")
```



```{r}
strategySuccess <- readRDS("./data/strategySuccess.rds")
#strategySuccess <- read.csv("../CulturalSystemscpp/SimulationResults.csv", na.strings = "nan")
data <- as.data.frame(strategySuccess)
library(data.table)
setDT(data)
setnames(data, c("numNodes", "blockedLearningStrat", "repl", "payoff_scaling", "blockedLayer", "numBlocked", "numSteps",'propBlocked', "sumPayoff", "sumPayoffUnblocked", "sumPayoffBlocked", "failed_learning_prop", "failed_learning_prop_blocked"))

#set first 8 columns to factor
data[ , (1:5) := lapply(.SD, factor), .SDcols = 1:5]

data[ , blockedLearningStrat := factor(blockedLearningStrat, levels = c(0,1,2,3,4,7), labels = c("Random", "Payoff", "Similarity", "Age-Based", "Conformity", "Similarity2"))] 
data[ , tree_func := factor(tree_func, levels = c(1,2), labels = c("flat", "constrained"))]

summary(mod1 <- lm(sumPayoffBlocked ~ blockedLearningStrat + numSteps + blockedLayer + propBlocked , data = data))

summary(mod2 <- lm(sumPayoffBlocked ~ blockedLearningStrat*blockedLayer*propBlocked, data = data))

#Probing the interaction numSteps:blockedLayer:propBlocked 
prepare_aggregated_data <- function(data, dependent_var, independent_vars) {
  aggregated_data <- data %>%
    group_by(across(all_of(independent_vars))) %>%
    summarise(
      mean_value = mean(get(dependent_var), na.rm = TRUE),
      SE = sd(get(dependent_var), na.rm = TRUE) / sqrt(n()),  # Standard Error
      n = n(),
      .groups = 'drop'
    ) %>%
    mutate(
      CI_lower = mean_value - (1.96 * SE),
      CI_upper = mean_value + (1.96 * SE)
    )
  
  return(aggregated_data)
}

dependent_var <- "sumPayoffUnblocked"
independent_vars <- c("blockedLearningStrat", "numSteps", "blockedLayer", "propBlocked")
#independent_vars <- c("blockedLearningStrat", "age_bias", "tree_func")
aggregated_data2 <- prepare_aggregated_data(data, dependent_var, independent_vars)

# Plotting the aggregated means
p <- ggplot(aggregated_data2, aes(x = propBlocked, y = mean_value, group = interaction(blockedLayer, numSteps), color = as.factor(blockedLayer))) +
  geom_smooth(aes(linetype = as.factor(numSteps), fill = as.factor(blockedLayer)), method = "loess", span = 4, alpha = 0.2, se = TRUE) +
  facet_wrap(~blockedLearningStrat, labeller = labeller(blockedLearningStrat = c(Random = "A) Random", Payoff = "B) Payoff", Similarity = "C) Similarity", Similarity2 = "Strategy: Similiarity 2", Conformity = "D) Conformity")), nrow = 1) +
  labs(title = "Average Payoff for Individuals with no Learning Difficulties (LD)", x = "Proportion of Population with LD", y = "Average Payoff per Learning Attempt", color = "Depth of Learning Difficulty", linetype = "Learning Steps Required\nto Compensate for LD", fill = "Depth of Learning Difficulty") +
  scale_color_manual(labels = c('1' = 'Layer 1', '2' = 'Layer 2', '3' = 'Layer 3'), values = c('1' = 'red2', '2' = 'gold1', '3' = 'green3')) +
  scale_fill_manual(labels = c('1' = 'Layer 1', '2' = 'Layer 2', '3' = 'Layer 3'), values = c('1' = 'red2', '2' = 'gold1', '3' = 'green3')) +
  scale_linetype_manual(values = c(1, 2, 3)) +
  guides(linetype = guide_legend(override.aes = list(color = "black"))) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), strip.text.x = element_text(size = 12, face = "bold"), legend.position = "top")
p
```



```{r}
data_long <- melt(data, 
                  id.vars = c("numNodes", "blockedLearningStrat", "repl", "payoff_scaling", 
                              "blockedLayer", "numBlocked", "numSteps", "propBlocked"),
                  measure.vars = c("sumPayoffUnblocked", "sumPayoffBlocked"),
                  variable.name = "group",
                  value.name = "payoff") 

summary(model <- lm(payoff ~ blockedLayer + numSteps + propBlocked + group + blockedLearningStrat, 
            data = data_long))

full_model <- lm(payoff ~ (blockedLayer + numSteps + propBlocked + group + blockedLearningStrat)^2, 
                 data = data_long)

# Perform forward selection
forward_model <- step(model, 
                      scope = list(lower = formula(model), upper = formula(full_model)),
                      direction = "forward")

# Summary of the final model after forward selection
summary(forward_model)
```
## Plot Results without payoff-scaling

```{r}
p2 <- ggplot(aggregated_data2, aes(x = propBlocked, y = mean_value, group = interaction(blockedLayer, numSteps), color = as.factor(blockedLayer))) +
  geom_smooth(aes(linetype = as.factor(numSteps), fill = as.factor(blockedLayer)), method = "loess", span = 4, alpha = 0.2, se = TRUE) +
  facet_wrap(~blockedLearningStrat, labeller = labeller(blockedLearningStrat = c(Random = "A) Random", Payoff = "B) Payoff", Similarity = "C) Similarity", Similarity2 = "Strategy: Similiarity 2", Conformity = "D) Conformity")),nrow = 1) +
  labs(title = "Average Payoff for Individuals with Learning Difficulties (LD)", x = "Proportion of Population with LD", y = "Average Payoff per Learning Attempt", color = "Depth of Learning Difficulty", linetype = "Learning Steps Required\nto Compensate for LD", fill = "Depth of Learning Difficulty") +
  scale_color_manual(labels = c('1' = 'Layer 1', '2' = 'Layer 2', '3' = 'Layer 3'), values = c('1' = 'red2', '2' = 'gold1', '3' = 'green3')) +
  scale_fill_manual(labels = c('1' = 'Layer 1', '2' = 'Layer 2', '3' = 'Layer 3'), values = c('1' = 'red2', '2' = 'gold1', '3' = 'green3')) +
  scale_linetype_manual(values = c(1, 2, 3)) +
  guides(linetype = guide_legend(override.aes = list(color = "black"))) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), strip.text.x = element_text(size = 12, face = "bold"), legend.position = "top")
print(p2)
```
```{r}
p <- ggplot(aggregated_data2, aes(x = age_bias, y = mean_value, group = tree_func, color = as.factor(tree_func), fill = as.factor(tree_func))) +
  geom_smooth(method = "loess", span = 4, alpha = 0.2, se = TRUE) +
  scale_color_manual(name = "Environment", values = c('turquoise','salmon')) +
  scale_fill_manual(name = "Environment", values = c('turquoise','salmon')) +
  facet_wrap(~blockedLearningStrat, labeller = labeller(blockedLearningStrat = c(Random = "A) Random", Payoff = "B) Payoff", Similarity = "C) Similarity", Similarity2 = "Strategy: Similiarity 2", Conformity = "D) Conformity")), nrow = 1) +
  labs(x = "Age Bias", y = "Average Payoff per Learning Attempt", color = "Environment", fill = "Environment") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), strip.text.x = element_text(size = 12, face = "bold"), legend.position = "none")
p

library(ggraph)
constrained_tree <- generate_rooted_tree()
constrained_plot <- ggraph::ggraph(constrained_tree, layout = layout.reingold.tilford(tree)) + 
  ggraph::geom_edge_link(arrow = arrow(type = "closed", length = unit(2, "mm")), start_cap = circle(3, 'mm'), end_cap = circle(3, 'mm')) +
  ggraph::geom_node_point(size = 5, color = "salmon") +
  ggtitle("Constrained Environment") +
  theme_void()

flat_tree <- generate_flat_tree()
flat_plot <- ggraph::ggraph(flat_tree, layout = layout_as_tree(tree)) + 
  ggraph::geom_edge_link(arrow = arrow(type = "closed", length = unit(2, "mm")), start_cap = circle(3, 'mm'), end_cap = circle(3, 'mm')) +
  ggraph::geom_node_point(size = 5, color = "turquoise") + 
  ggtitle("Unconstrained Environment ") +
  theme_void()
flat_plot

library(patchwork)
p2 <- p + (constrained_plot / flat_plot) + plot_layout(widths = c(2, 1))
p2

```




```{r}
p <-ggplot(aggregated_data2, aes(x = propBlocked, y = mean_value, group = interaction(blockedLayer, numSteps), color = as.factor(blockedLayer))) +
  geom_smooth(aes(linetype = as.factor(numSteps), fill = as.factor(blockedLayer)), method = "lm", alpha = 0.2, se = TRUE) +
  facet_wrap(~blockedLearningStrat, labeller = labeller(blockedLearningStrat = c(Random = "Strategy: Random", Payoff = "Strategy: Payoff", Similarity = "Strategy: Similarity", Similarity2 = "Strategy: Similiarity 2", Conformity = "Strategy: Conformity")), nrow = 1) +
  labs(title = "Average Payoff for Individuals with Learning Difficulties (LD)",
       x = "Proportion of Population with LD",
       y = "Average Payoff per Learning Attempt",
       color = "LD Depth",
       linetype = "Number of Learning Steps",
       fill = "LD Depth") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        strip.text.x = element_text(size = 12, face = "bold"))

p
```

```{r}
ggplot(aggregated_data2, aes(x = propBlocked, y = mean_value, group = interaction(blockedLayer, as.factor(numSteps)), color = as.factor(numSteps))) +
  geom_line(aes(linetype = as.factor(blockedLayer))) +
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper), width = 0.01) +
  facet_wrap(~blockedLearningStrat, labeller = labeller(blockedLearningStrat = c(Random = "Strategy: Random", Payoff = "Strategy: Payoff", Similarity = "Strategy: Similarity", Similarity2 = "Strategy: Similiarity 2", Conformity = "Strategy: Conformity"))) +
  labs(title = "Average Payoff for Individuals with Learning Difficulties (LD)",
       x = "Proportion of Population with LD",
       y = "Average Payoff per Learning Attempt",
       color = "Number of Learning Steps",
       linetype = "LD Depth") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text.x = element_text(size = 12, face = "bold"))
```



```{r}

tr_sums_blocked <- readRDS("./data/tr_sums_blocked.rds")
failure_sums_blocked <- readRDS("./data/failure_sums_blocked.rds")

if (max(unlist(failure_sums_blocked)) > 50) {
  print("Warning: failure_sums_blocked contains values greater than 50")
}

tree <- attributes(tr_sums_blocked)$tree

aux_nodes <- which(!1:gorder(tree) %in% 1:16)
blocked_nodes <- attributes(tree)$blockedTraits

# Edge colors
targets <- ends(tree, E(tree))[, 2]
edge_colors <- rep("darkgrey", ecount(tree))
edge_colors[targets %in% aux_nodes] <- "forestgreen"
edge_colors[targets %in% blocked_nodes] <- "firebrick"


# Size scaling
min_new <- 10
max_new <- 30


col_palette <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan", "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))(51)
break_points <- seq(0, 129, length.out = 52)

legend_colors <- col_palette[c(1, 11, 21, 31, 41, 51)] 

animation::saveGIF({
  for(t in seq(1, 2000, 5)) {
    tr_sums <- tr_sums_blocked[[t]]
    scaled_sizes <- (tr_sums - min(tr_sums)) / (max(tr_sums) - min(tr_sums)) * (max_new - min_new) + min_new
    
    bin_indices <- findInterval(failure_sums_blocked[[t]], vec = break_points, left.open = TRUE)
    vertex_colors <- col_palette[bin_indices]

    plot(tree, layout = layout.reingold.tilford(tree),
         vertex.size = scaled_sizes,
         vertex.label = tr_sums,
         vertex.label.color = "white",
         vertex.color = vertex_colors,
         edge.color = edge_colors,
         main = "Learning Strategy = Payoff | Blocked Layer = 1", sub = paste("Time Step", t))
 
    legend("topleft", legend=c("0", "10", "20", "30", "40", "50"), fill=legend_colors, title="Failure Sum")
  }
}, movie.name = "layer_1_payoff.gif", interval = 1/50)
```

```{r}
library(magick)

gif_layer_1 <- image_read("layer_1.gif")
gif_layer_2 <- image_read("layer_2.gif")
gif_layer1_payoff <- image_read("layer_1_payoff.gif")
gif_layer_2_payoff <- image_read("layer_2_payoff.gif")

# Verify that the number of frames in each GIF is the same prior to combining
# This might require adjusting your GIFs to have the same duration and frame rate 

# Combine the GIFs into a 2x2 grid
gif_combined <- image_montage(
  c(gif_layer_1, gif_layer_2, gif_layer1_payoff, gif_layer_2_payoff), 
  tile = "2x2", 
  geometry = "1000x1000+0+0"
)

# Write the combined GIF to a new file
image_write_gif(gif_combined, "combined_grid.gif")
```




```{r}
trait_dist <- readRDS("trait_dist.rds")

traitdepths <- list(
 `1` = 2,
 `2` = c(3,4),
 `3` = c(5:8),
 `4` = c(9:16),
 `5` = c(17,18)
)

trait_dist_long <- as.data.frame(trait_dist) %>% 

  tibble::rownames_to_column("Time") %>% 

  pivot_longer(-Time, names_to = "Trait", values_to = "Proportion")

trait_dist_long$Depth <- unlist(traitdepths)[as.character(trait_dist_long$Trait)]

```


















