// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getTraitLearningProbability
std::vector<double> getTraitLearningProbability(Rcpp::IntegerMatrix repertoires, int ind, Rcpp::List requirements, std::vector<int> learnableTraits);
RcppExport SEXP _RcppFunctions_getTraitLearningProbability(SEXP repertoiresSEXP, SEXP indSEXP, SEXP requirementsSEXP, SEXP learnableTraitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type repertoires(repertoiresSEXP);
    Rcpp::traits::input_parameter< int >::type ind(indSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type requirements(requirementsSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type learnableTraits(learnableTraitsSEXP);
    rcpp_result_gen = Rcpp::wrap(getTraitLearningProbability(repertoires, ind, requirements, learnableTraits));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppFunctions_getTraitLearningProbability", (DL_FUNC) &_RcppFunctions_getTraitLearningProbability, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppFunctions(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
